[package]
name = "vsdb"
version = "0.20.0"
authors = ["fanhui.x@gmail.com"]
edition = "2021"
description = "Versioned Stateful DataBase, mainly used in blockchain scene."
homepage = "https://github.com/ccmlm/vsdb"
repository = "https://github.com/ccmlm/vsdb"
keywords = ["git", "leveldb", "rocksdb", "version", "vcs"]
categories = ["database-implementations", "data-structures", "algorithms", "caching"]
license = "MIT"

[dependencies]
ruc = "1.0.7"
once_cell = "1.10.0"
serde = { version = "1.0.136", features = ["derive"] }
parking_lot = "0.12.0"
fast-math = "0.1"

primitive-types-0-11 = { package = "primitive-types", version = "0.11", default-features = false }
primitive-types-0-10 = { package = "primitive-types", version = "0.10", default-features = false }

sha3 = { version = "0.10.1", optional = true }
vsdb_derive = { version = "0.2.3", optional = true }
bcs = { version = "0.1.3", optional = true }
msgpack = { package = "rmp-serde", version = "1.0.0", optional = true }
rocksdb = { version = "0.18.0", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
sled = { package = "vsdbsled", version = "0.34.7-patched", features = ["compression", "io_uring"], optional = true }

[target.'cfg(not(target_os = "linux"))'.dependencies]
sled = { package = "vsdbsled", version = "0.34.7-patched", features = ["compression"], optional = true }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"]}
once_cell = "1.9.0"
hex = "0.4.3"
rand = "0.8.5"

[features]
default = ["derive", "sled_engine", "msgpack_codec"]
derive = ["vsdb_derive"]
sled_engine = ["sled"]
rocks_engine = ["rocksdb"]
msgpack_codec = ["msgpack"]
bcs_codec = ["bcs"]
merkle = ["sha3"]

[[bench]]
name = "basic"
harness = false

[profile.dev]
incremental = false
overflow-checks = true

[profile.release]
codegen-units = 1
incremental = false
overflow-checks = false

[profile.bench]
codegen-units = 1
incremental = false
overflow-checks = false

[[example]]
name = "blockchain_state"

[[example]]
name = "web_server"
