[package]
name = "vsdb"
version = "0.9.2"
authors = ["fanhui.x@gmail.com"]
edition = "2021"
description = "Versioned Stateful DataBase, mainly used in blockchain scene."
homepage = "https://github.com/ccmlm/vsdb"
repository = "https://github.com/ccmlm/vsdb"
keywords = ["version", "blockchain", "database"]
categories = ["DataBase"]
license = "MIT"

[dependencies]
ruc = "0.6"
bincode = "1.3"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
sled = { version = "0.34", features = ["compression"] }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"]}

[features]
default = []

[[bench]]
name = "basic"
harness = false
