[package]
name = "bnc"
version = "0.1.1"
authors = ["FindoraNetwork"]
edition = "2018"

[dependencies]
rand = "0.8.3"
bincode = "1.3.2"
serde_json = "1.0.64"
serde = { version = "1.0.124", features = ["derive"] }
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
lazy_static = { version = "1.4.0" }

sled = { git = "https://github.com/FindoraNetwork/sled.git", branch = "main" }

[dev-dependencies]
criterion = "0.3"

[features]
default = []
debug_env = []
compress = ["sled/compression"]

[[bench]]
name = "cache"
harness = false
