[package]
name = "vsdb"
version = "0.9.2"
authors = ["fanhui.x@gmail.com"]
edition = "2021"
description = "Versioned Stateful DataBase, mainly used in blockchain scene."
homepage = "https://github.com/ccmlm/vsdb"
repository = "https://github.com/ccmlm/vsdb"
keywords = ["version", "blockchain", "database"]
categories = ["DataBase"]
license = "MIT"

[dependencies]
ruc = "0.6"
bcs = "0.1.3"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
sled = { git = "https://gitee.com/kt10/sled.git", branch = "v0.34.7-patched", features = ["compression", "io_uring"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
sled = { git = "https://gitee.com/kt10/sled.git", branch = "v0.34.7-patched", features = ["compression"] }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"]}

[features]
default = []

[[bench]]
name = "basic"
harness = false

[profile.dev]
incremental = false
overflow-checks = true

[profile.release]
codegen-units = 1
incremental = false
overflow-checks = false

[profile.bench]
codegen-units = 1
incremental = false
overflow-checks = false
