[package]
name = "bnc"
version = "0.1.1"
authors = ["FindoraNetwork"]
edition = "2018"

[dependencies]
rand = "0.8.3"
bincode = "1.3.2"
serde_json = "1.0.64"
serde = { version = "1.0.124", features = ["derive"] }
lazy_static = { version = "1.4.0" }

rocksdb = { version = "0.17.0", default-features = false, features = ["lz4"] }

ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }

[dev-dependencies]
criterion = "0.3.5"

[features]
default = []
compress = ["rocksdb/lz4"]

[[bench]]
name = "cache"
harness = false
