[package]
name = "bnc"
version = "0.2.0"
authors = ["FindoraNetwork"]
edition = "2018"

[dependencies]
rand = "0.8.3"
bincode = "1.3.2"
serde_json = "1.0.64"
serde = { version = "1.0.124", features = ["derive"] }
lazy_static = { version = "1.4.0" }
num_cpus = "1.13.0"

rocksdb = { version = "0.17.0", default-features = false, features = ["lz4"], optional = true }

ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }

[dev-dependencies]
criterion = "0.3.5"

[features]
default = ["diskcache"]
diskcache = ["rocksdb"]

[[bench]]
name = "cache"
harness = false
