[package]
name = "vsdb"
version = "0.11.3"
authors = ["fanhui.x@gmail.com"]
edition = "2021"
description = "Versioned Stateful DataBase, mainly used in blockchain scene."
homepage = "https://github.com/ccmlm/vsdb"
repository = "https://github.com/ccmlm/vsdb"
keywords = ["git", "leveldb", "rocksdb", "version", "vcs"]
categories = ["database-implementations", "data-structures", "algorithms", "caching"]
license = "MIT"

[dependencies]
ruc = "0.6"
once_cell = "1.9.0"
serde = { version = "1.0", features = ["derive"] }
parking_lot = "0.11.2"
fast-math = "0.1"
sha3 = "0.10"
vsdb_derive = "0.1"

serde_cbor = { version = "0.11", optional = true }
bcs = { version = "0.1.3", optional = true }
rocksdb = { version = "0.17.0", optional = true }
num_cpus = { version = "1.13", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
sled = { package = "vsdbsled", version = "0.34.7-patched", features = ["compression", "io_uring"], optional = true }

[target.'cfg(not(target_os = "linux"))'.dependencies]
sled = { package = "vsdbsled", version = "0.34.7-patched", features = ["compression"], optional = true }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"]}
once_cell = "1.9.0"
hex = "0.4.3"
bcs = "0.1.3"

[features]
default = ["sled_engine", "cbor_ende"]

cbor_ende = ["serde_cbor"]
sled_engine = ["sled"]

bcs_ende = ["bcs"]
rocks_engine = ["rocksdb", "num_cpus"]

[[bench]]
name = "basic"
harness = false

[profile.dev]
incremental = false
overflow-checks = true

[profile.release]
codegen-units = 1
incremental = false
overflow-checks = false

[profile.bench]
codegen-units = 1
incremental = false
overflow-checks = false

[[example]]
name = "blockchain_state"

[[example]]
name = "web_server"
