[package]
name = "vsdb"
version = "0.0.1"
authors = ["fanhui.x@gmail.com"]
edition = "2021"
description = "A versioned state database, mainly used to keep versioned blockchain state."
keywords = ["versioned", "cache", "database"]
categories = ["database"]
license = "MIT"

[dependencies]
rand = "0.8.3"
bincode = "1.3.2"
serde_json = "1.0.64"
serde = { version = "1.0.124", features = ["derive"] }
lazy_static = { version = "1.4.0" }
num_cpus = "1.13.0"
ruc = "0.6.2"

rocksdb = { version = "0.17.0", default-features = false, features = ["lz4"], optional = true }

[dev-dependencies]
criterion = "0.3.5"

[features]
default = ["diskcache"]
diskcache = ["rocksdb"]

[[bench]]
name = "cache"
harness = false
